version: '2'
services:
  redis:
    restart: always
    image: "redis:3.2"
    volumes:
    - ./data:/data
    command: redis-server --appendonly yes
    expose:
      - 6379
  cx_web:
    extends: cx_cron
    restart: always
    command: uwsgi /cx/uwsgi.ini
    ports:
    - 8080:5000
    
  cx_cron:
    working_dir: "/cx"
    volumes:
    - .:/cx
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: "python cx_cron.py"

